# Site settings
title: Doctor Developer
header-img: img/home-bg.png
email: etter.dt@gmail.com
copyright_name: danetter17
description: > # this means to ignore newlines until "baseurl:"
  My journey from the biological sciences to computer science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  danetter17
learn_profile: danetter17
email_username: etter.dt@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
